---
-  name: configure DNS client
   template:
     src: resolv.conf
     dest: /etc/resol.conf

- name: Install ntp
  yum:
    name: ntp
    state: present
    tags: ntp
  
- name: copy ntp file #once this task completes notify task notifies to handlers to restart service
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    tags: ntp
  notify: restart ntp service
